services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vw.nicolasyates.com"
    labels:
      caddy: vw.nicolasyates.com
      caddy.reverse_proxy: "localhost:8001"
    volumes:
      - ./vw-data/:/data/
    ports:
      - 127.0.0.1:8001:80
